# Generate sample device file output for v2.31 showing clean XSCEND naming
Write-Host "Generating Sample Device File Output - v2.31" -ForegroundColor Green
Write-Host "=============================================" -ForegroundColor Green

# Create sample device file content that would be generated by v2.31
$sampleDevices = @(
    [PSCustomObject]@{
        Status = "OK"
        Name = "XSX-21"  # Clean name from API (no IP suffix)
        Location = "Windsor"
        Type = "XSCEND"
        IPs = "192.168.12.21,192.168.12.22"
    },
    [PSCustomObject]@{
        Status = "OK"
        Name = "XSX-23"  # Clean name from API (no IP suffix)
        Location = "Windsor" 
        Type = "XSCEND"
        IPs = "192.168.12.23,192.168.12.24"
    },
    [PSCustomObject]@{
        Status = "OK"
        Name = "MD8000-Core"
        Location = "Windsor"
        Type = "MD8000-MGMT"
        IPs = "192.168.12.10"
    },
    [PSCustomObject]@{
        Status = "OK"
        Name = "XSCEND-Device-192.168.12.30"  # Fallback name (no API name available)
        Location = "Windsor"
        Type = "XSCEND"
        IPs = "192.168.12.30"
    }
)

# Generate device file content
$outputPath = "Sample_DiscoveredDevices_v2.31.csv"
$currentDateTime = Get-Date -Format "yyyy-MM-dd HH:mm:ss"

$content = @"
# DiscoverSubnet Version 2.31 Report
# Generated: $currentDateTime  
# IP Ranges Scanned: 192.168.12.0
# SNMP Communities: public,medialinks
# Max Parallel Scans: 20
# Total Devices Found: $($sampleDevices.Count)
#
Status;Name;Location;Type;IP(s)
"@

# Add device entries
foreach ($device in $sampleDevices) {
    $content += "`n$($device.Status);$($device.Name);$($device.Location);$($device.Type);$($device.IPs)"
}

# Save to file
$content | Out-File -FilePath $outputPath -Encoding UTF8
Write-Host "Sample device file created: $outputPath" -ForegroundColor Cyan

# Display the content
Write-Host "`nSample Device File Content:" -ForegroundColor Yellow
Write-Host "===========================" -ForegroundColor Yellow
Get-Content $outputPath | ForEach-Object {
    if ($_ -match "^OK;XSX-") {
        Write-Host $_ -ForegroundColor Green  # Highlight XSCEND devices
    } elseif ($_ -match "^OK;XSCEND-Device-") {
        Write-Host $_ -ForegroundColor Gray   # Fallback XSCEND devices
    } elseif ($_ -match "^OK;") {
        Write-Host $_ -ForegroundColor White  # Other devices
    } else {
        Write-Host $_ -ForegroundColor DarkGray  # Headers and comments
    }
}

Write-Host "`nKey Improvements in v2.31:" -ForegroundColor Yellow
Write-Host "✓ XSX-21 and XSX-23 use clean names (no IP suffixes)" -ForegroundColor Green
Write-Host "✓ Only fallback devices get IP-suffixed names" -ForegroundColor Green
Write-Host "✓ Proper device separation maintained" -ForegroundColor Green
Write-Host "✓ Compatible with EMS/NMS systems expecting clean device names" -ForegroundColor Green